<html> <head> <title>Thanks</title> <meta content='Hacked by Me' property='og:title'/> <meta content='article' property='og:type'/> <meta content='http://lnhuaxun.com/x_.htm' property='og:url'/>  <body bgcolor="black"> <style> h1 { text-align: center; color: #3335cf; font-size: 35px; font-family: Arial Narrow, sans-serif; font-style: garamond; text-shadow: 100vmax #f00505;> text-shadow: 0px 0px 0px #f00505;> </style> <h1>THANKS FOR MY FRIENDS</h1> <center> <img src="https://www.upload.ee/image/9337294/20181223_192931.png" height="450" width="450"> </center> <center><font color=red size=3 face=courier new>prayfor<font color=white>banten dan lampung</font></center> <center><font color=#077f01 size=5 face=courier new>Hacked by mr.4k427</font><center> <center><font color=#c6c5c4 size=2 face=courier new>[ <font> azharfrendly@gmail.com<font color=#c6c5c4> ]</font></center><table width=820px><td align=center><span style='font: 15px Courier;size:15px;color:#9E9E9E;'><strong><marquee behavior="alternate" scrollamount="5" style="border:1px solid;" width="70%"><font color="white" face="courier">-=|[TUAN N1CKN4M3] [ZMLDN CYBER] [Bubbllegum] [MR.4K427] =-</center></font></marquee></div>
<marquee scrollamount="150" direction="left" width="50%"><font color="#FF0000" size="+3" face="harrington">__________________________________</font></marquee><marquee scrollamount="150" direction="Right" width="50%"><font color="#FFFFFF" size="+3" face="harrington">__________________________________</marquee></font></div>

<center><font color=red size=4 face=courier new>kami turut mengucapkan terimakasih</font><center><font color=red size=4 face=courier new>atas ucapan kalian yang turut berduka cita atas</font><center><font color=red size=4 face=courier new>terjadinya bencana alam di daerah kami</font><center><font color=red size=4 face=courier new>(pandeglang) kami dari team pandeglang blackhat meminta doa kepada kalian semua</font><center><font color=red size=4 face=courier new>semoga daerah kami tidak terjadi lagi</font><center><font color=red size=4 face=courier new>bencaca alam kembali thks</font>
<marquee scrollamount="150" direction="left" width="50%"><font color="#FF0000" size="+3" face="harrington">__________________________________</font></marquee><marquee scrollamount="150" direction="Right" width="50%"><font color="#FFFFFF" size="+3" face="harrington">__________________________________</marquee></font></div>





